// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmicbet/wta/v1beta1/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/duration"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	PrizePercentage         github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=prize_percentage,json=prizePercentage,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"prize_percentage"`
	CommunityPoolPercentage github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=community_pool_percentage,json=communityPoolPercentage,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"community_pool_percentage"`
	BurnPercentage          github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=burn_percentage,json=burnPercentage,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"burn_percentage"`
	DrawDuration            time.Duration                          `protobuf:"bytes,4,opt,name=draw_duration,json=drawDuration,proto3,stdduration" json:"draw_duration"`
	TicketPrice             types.Coin                             `protobuf:"bytes,5,opt,name=ticket_price,json=ticketPrice,proto3" json:"ticket_price"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce4ff2a375989179, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDrawDuration() time.Duration {
	if m != nil {
		return m.DrawDuration
	}
	return 0
}

func (m *Params) GetTicketPrice() types.Coin {
	if m != nil {
		return m.TicketPrice
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Params)(nil), "cosmicbet.wta.v1beta1.Params")
}

func init() {
	proto.RegisterFile("cosmicbet/wta/v1beta1/params.proto", fileDescriptor_ce4ff2a375989179)
}

var fileDescriptor_ce4ff2a375989179 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xbf, 0x8e, 0xd3, 0x30,
	0x1c, 0xc7, 0x13, 0x5a, 0x2a, 0x48, 0x0b, 0x45, 0x11, 0x88, 0xb6, 0x83, 0x5b, 0x75, 0x80, 0x2e,
	0xd8, 0x2a, 0x3c, 0x01, 0x81, 0x01, 0xb6, 0xa8, 0x0b, 0x82, 0x25, 0x72, 0x1c, 0x13, 0x4c, 0x93,
	0xfc, 0x22, 0xc7, 0xa1, 0xf4, 0x9e, 0xe2, 0xc6, 0x7b, 0x92, 0x7b, 0x86, 0x8e, 0x1d, 0x4f, 0x37,
	0xf4, 0x4e, 0xed, 0x8b, 0x9c, 0x9c, 0x7f, 0x8a, 0x6e, 0xec, 0x14, 0xcb, 0xfa, 0x7d, 0x3f, 0x1f,
	0x3b, 0x5f, 0x5b, 0x73, 0x06, 0x59, 0x2c, 0x98, 0xcf, 0x15, 0xd9, 0x28, 0x4a, 0xfe, 0x2d, 0x7d,
	0xae, 0xe8, 0x92, 0xa4, 0x54, 0xd2, 0x38, 0xc3, 0xa9, 0x04, 0x05, 0xf6, 0x9b, 0x66, 0x06, 0x6f,
	0x14, 0xc5, 0xd5, 0xcc, 0x04, 0x85, 0x00, 0x61, 0xc4, 0x49, 0x31, 0xe4, 0xe7, 0xbf, 0x49, 0x90,
	0x4b, 0xaa, 0x04, 0x24, 0x65, 0x6c, 0xf2, 0x3a, 0x84, 0x10, 0x8a, 0x25, 0xd1, 0xab, 0x6a, 0x17,
	0x69, 0x18, 0x64, 0xc4, 0xa7, 0x19, 0x6f, 0x74, 0x0c, 0x44, 0x95, 0x9a, 0x5f, 0x77, 0xac, 0x9e,
	0x5b, 0xd8, 0xed, 0x9f, 0xd6, 0xab, 0x54, 0x8a, 0x0b, 0xee, 0xa5, 0x5c, 0x32, 0x9e, 0x28, 0x1a,
	0xf2, 0x91, 0x39, 0x33, 0x17, 0xcf, 0x1d, 0xbc, 0x3b, 0x4c, 0x8d, 0xdb, 0xc3, 0xf4, 0x5d, 0x28,
	0xd4, 0x9f, 0xdc, 0xc7, 0x0c, 0x62, 0x52, 0x71, 0xcb, 0xcf, 0x87, 0x2c, 0x58, 0x13, 0xb5, 0x4d,
	0x79, 0x86, 0xbf, 0x27, 0x6a, 0x35, 0x2c, 0x38, 0x6e, 0x83, 0xb1, 0xff, 0x5a, 0x63, 0x06, 0x71,
	0x9c, 0x27, 0x42, 0x6d, 0xbd, 0x14, 0x20, 0x6a, 0x3b, 0x9e, 0x9c, 0xe5, 0x78, 0xdb, 0x00, 0x5d,
	0x80, 0xa8, 0xe5, 0xfa, 0x61, 0x0d, 0xfd, 0x5c, 0x26, 0x6d, 0x43, 0xe7, 0x2c, 0xc3, 0x4b, 0x8d,
	0x69, 0x81, 0xbf, 0x59, 0x2f, 0x02, 0x49, 0x37, 0x5e, 0xfd, 0xdf, 0x47, 0xdd, 0x99, 0xb9, 0xe8,
	0x7f, 0x1c, 0xe3, 0xb2, 0x18, 0x5c, 0x17, 0x83, 0xbf, 0x56, 0x03, 0xce, 0x33, 0x6d, 0xbc, 0xba,
	0x9b, 0x9a, 0xab, 0x81, 0x4e, 0xd6, 0xfb, 0xb6, 0x63, 0x0d, 0x94, 0x60, 0x6b, 0xae, 0xbc, 0x54,
	0x0a, 0xc6, 0x47, 0x4f, 0x2b, 0x50, 0x79, 0x0c, 0xac, 0xbb, 0xaa, 0x6b, 0xc7, 0x5f, 0x40, 0x24,
	0x4e, 0x57, 0x83, 0x56, 0xfd, 0x32, 0xe4, 0xea, 0x8c, 0xf3, 0x79, 0x77, 0x44, 0xe6, 0xfe, 0x88,
	0xcc, 0xfb, 0x23, 0x32, 0x2f, 0x4f, 0xc8, 0xd8, 0x9f, 0x90, 0x71, 0x73, 0x42, 0xc6, 0xaf, 0xf7,
	0x8f, 0xee, 0x57, 0x3e, 0xb7, 0x88, 0x07, 0x21, 0x97, 0xe4, 0x7f, 0xf1, 0xee, 0x8a, 0x4b, 0xfa,
	0xbd, 0xe2, 0xc4, 0x9f, 0x1e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x21, 0xce, 0x54, 0x8b, 0x95, 0x02,
	0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TicketPrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	n2, err2 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.DrawDuration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.DrawDuration):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	{
		size := m.BurnPercentage.Size()
		i -= size
		if _, err := m.BurnPercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.CommunityPoolPercentage.Size()
		i -= size
		if _, err := m.CommunityPoolPercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.PrizePercentage.Size()
		i -= size
		if _, err := m.PrizePercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PrizePercentage.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.CommunityPoolPercentage.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BurnPercentage.Size()
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.DrawDuration)
	n += 1 + l + sovParams(uint64(l))
	l = m.TicketPrice.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrizePercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PrizePercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommunityPoolPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommunityPoolPercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnPercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrawDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.DrawDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TicketPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TicketPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
